spring:
  application:
    name: track-531
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  mustache:
    cache: false

jackson:
  serialization:
    indent_output: true